# Error handling with file I/O

When working with external resources, errors are bound to happen at some point. When reading a file, there's a chance that the file isn't there, or it could be deleted halfway through reading it. Because of that, you need to be able to handle a `FileNotFoundException`.

There's another issue with this line of code you saw earlier:

```
Scanner dataInput = new Scanner(dataFile);
```

The `Scanner` opens the file for reading, but nothing closes the file. The file might close when the program ends, but opening a file can put a lock on it, preventing other applications from working with the file. You want to make sure you only have the file open for as long as you need it and no longer than that.

You can handle both of these issues with a new kind of `try` block: the `try-with-resources` block:

```java
try (Scanner dataInput = new Scanner(dataFile)) {
    while(dataInput.hasNextLine()) {
        String lineOfInput = dataInput.nextLine();
        ...
    }
} catch (FileNotFoundException e) {
    System.err.println("The file does not exist.");
}
```

Because you're passing the `Scanner` creation to the `try` block, this both closes the file once the `try` block completes and catches a `FileNotFoundException` if something happens with the file while reading it. Always use this style of code whenever you open a file for reading or writing.